default["tomcat_latest"]["tomcat_version"] = "7"
default["tomcat_latest"]["tomcat_install_loc"] = "/usr/local"
default["tomcat_latest"]["direct_download_version"] = "7.0.67"
default["vagrant_tomcat"]["tomcat_home"] = "#{node["tomcat_latest"]["tomcat_install_loc"]}/tomcat/apache-tomcat"
default['tomcat_latest']['tomcat_user'] = "bjk1456"
