# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "centos-6.7"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  

  config.vbguest.auto_update = false

  config.vm.provision "file", source: "~/vagrant/files/git-config", destination: "~/.gitconfig"

  config.vm.provision "shell", path: "https://raw.githubusercontent.com/bjk1456/Vagrant/master/scripts/centos-common.sh"

  config.vm.define "web" do |web|
    web.vm.hostname = "web-server"

    web.vm.network "forwarded_port", guest: 80, host: 8080

    web.vm.network "private_network", ip: "192.168.10.3"

    web.vm.provision "shell", path: "https://raw.githubusercontent.com/bjk1456/Vagrant/master/scripts/centos-web.sh"

  end

  config.vm.define "db" do |db|
    db.vm.hostname = "database-server"

    db.vm.network "private_network", ip: "192.168.10.2"

    db.vm.provision "shell", path: "https://raw.githubusercontent.com/bjk1456/Vagrant/master/scripts/centos-database.sh"

  end

  

end
